---
schema-version: '1.0'
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-v1
    args: -e JAVA_HOME=/opt/java/openjdk-11
build:
  name: OpenSearch
  version: 1.3.1
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: tags/1.3.1
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: tags/1.3.1.0
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: tags/1.3.1.0
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: tags/1.3.1.0
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: tags/1.3.1.0
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: tags/1.3.1.0
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: tags/1.3.1.0
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
